trigger:
  branches:
    include:
    - '*'
    exclude:
    - features/*
    - fixes/*
    - sandbox/*
  paths:
    include:
    - .azure/pipelines/arm.yml
    - .azure/pipelines/jobs/arm/*
    - .azure/pipelines/steps/arm/*
    - deploy/Distech.CloudRelay.ARM/*

jobs:
- job: empty
  condition: false
